const ToolsData = [
  {
    id: 1,
    name: 'Depictor',
    description: 'A tool for creating diagrams and flowcharts',
    link: 'https://depictor.app/',
    category: 'Design',
  },
  {
    id: 2,
    name: 'Translate',
    description: 'A tool for translating text',
    link: 'https://translate.google.com/',
    category: 'Design',
  },
  {
    id: 3,
    name: 'QSML',
    description: 'A tool for creating and editing QSML files',
    link: 'https://qsml.app/',
    category: 'Design',
  },
  {
    id: 4,
    name: 'TinkerCell',
    description: 'A tool for creating and editing TinkerCell files',
    link: 'https://tinkercell.com/',
    category: 'Design',
  },
  {
    id: 5,
    name: 'Minefield',
    description: 'A tool for creating and editing Minefield files',
    link: 'https://minefield.app/',
    category: 'Design',
  },
  {
    id: 6,
    name: 'BioModels Database',
    description: 'A tool for creating and editing BioModels Database files',
    link: 'https://www.ebi.ac.uk/biomodels/',
    category: 'Design',
  },
  {
    id: 7,
    name: 'Close to me',
    description: 'A tool for creating and editing Close to me files',
    link: 'https://www.closetome.app/',
    category: 'Design',
  },
  {
    id: 8,
    name: 'MultiSearch',
    description: 'A tool for creating and editing MultiSearch files',
    link: 'https://multisearch.app/',
    category: 'Design',
  },
  {
    id: 9,
    name: 'Visualize',
    description: 'A tool for creating and editing Visualize files',
    link: 'https://visualize.app/',
    category: 'Design',
  },
  {
    id: 10,
    name: 'BioSimulators',
    description: 'A tool for creating and editing BioSimulators files',
    link: 'https://biosimulators.org/',
    category: 'Design',
  },
  {
    id: 11,
    name: 'Wikidata Skim',
    description: 'A tool for creating and editing Wikidata Skim files',
    link: 'https://skim.wmflabs.org/',
    category: 'Design',
  },
  {
    id: 12,
    name: 'Wdqs-proxy',
    description: 'A tool for creating and editing Wdqs-proxy files',
    link: 'https://wdqs-proxy.toolforge.org/',
    category: 'Design',
  },
  {
    id: 13,
    name: 'Wrdz',
    description: 'A tool for creating and editing Wrdz files',
    link: 'https://wrdz.toolforge.org/',
    category: 'Design',
  },
  {
    id: 14,
    name: 'Wikidata Query Service',
    description: 'A tool for creating and editing Wikidata Query Service files',
    link: 'https://query.wikidata.org/',
    category: 'Design',
  },
  {
    id: 15,
    name: 'Molecular Design Toolkit',
    description: 'A tool for creating and editing Molecular Design Toolkit files',
    link: 'https://molecular-design-toolkit.org/',
    category: 'Design',
  },
  {
    id: 16,
    name: 'D3',
    description: 'A tool for creating and editing D3 files',
    link: 'https://d3js.org/',
    category: 'Design',
  },
  {
    id: 17,
    name: 'D3.js',
    description: 'A tool for creating and editing D3.js files',
    link: 'https://d3js.org/',
    category: 'Design',
  },
  {
    id: 18,
    name: 'D5.js',
    description: 'A tool for creating and editing D3.js files',
  },
];

export default ToolsData;
